### POST to create patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Demo Patient",
  "email": "demo_patient@gmail.com",
  "address": "123 Demo address",
  "dateOfBirth": "1998-10-19",
  "registeredDate": "2025-06-05"
}

###